import './globals.scss';
import { Inter, Rubik_Scribble } from 'next/font/google';
import Header from './components/Header';

// Font files can be colocated inside of `app`
const rubikScribble = Rubik_Scribble({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-rubik-scribble',
  weight: ['400'],
});

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  display: 'swap',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${inter.variable} ${rubikScribble.variable}`}>
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
